#!/usr/bin/env python3
"""
White-Box AES-256 Table Generator for LianYu — CORRECTED

Generates C header with pre-computed lookup tables embedding
the AES-256 key. Run at build time to produce wb_tables.inc.

Usage:
    python3 tools/gen_wb_tables.py --key hex:0123456789abcdef... > wb_tables.inc
    python3 tools/gen_wb_tables.py --key random > wb_tables.inc

Architecture (Chow-style):
  - Round key is embedded INSIDE the T-Box via SBOX[x ^ rk]
  - No separate AddRoundKey step needed
  - Checksums are computed from actual table data
  - Inverse T-Boxes use InvSubBytes embedded inside
"""

import sys
import os
import argparse
from hashlib import sha256

# AES S-Box (standard)
SBOX = [
    0x63,0x7c,0x77,0x7b,0xf2,0x6b,0x6f,0xc5,0x30,0x01,0x67,0x2b,0xfe,0xd7,0xab,0x76,
    0xca,0x82,0xc9,0x7d,0xfa,0x59,0x47,0xf0,0xad,0xd4,0xa2,0xaf,0x9c,0xa4,0x72,0xc0,
    0xb7,0xfd,0x93,0x26,0x36,0x3f,0xf7,0xcc,0x34,0xa5,0xe5,0xf1,0x71,0xd8,0x31,0x15,
    0x04,0xc7,0x23,0xc3,0x18,0x96,0x05,0x9a,0x07,0x12,0x80,0xe2,0xeb,0x27,0xb2,0x75,
    0x09,0x83,0x2c,0x1a,0x1b,0x6e,0x5a,0xa0,0x52,0x3b,0xd6,0xb3,0x29,0xe3,0x2f,0x84,
    0x53,0xd1,0x00,0xed,0x20,0xfc,0xb1,0x5b,0x6a,0xcb,0xbe,0x39,0x4a,0x4c,0x58,0xcf,
    0xd0,0xef,0xaa,0xfb,0x43,0x4d,0x33,0x85,0x45,0xf9,0x02,0x7f,0x50,0x3c,0x9f,0xa8,
    0x51,0xa3,0x40,0x8f,0x92,0x9d,0x38,0xf5,0xbc,0xb6,0xda,0x21,0x10,0xff,0xf3,0xd2,
    0xcd,0x0c,0x13,0xec,0x5f,0x97,0x44,0x17,0xc4,0xa7,0x7e,0x3d,0x64,0x5d,0x19,0x73,
    0x60,0x81,0x4f,0xdc,0x22,0x2a,0x90,0x88,0x46,0xee,0xb8,0x14,0xde,0x5e,0x0b,0xdb,
    0xe0,0x32,0x3a,0x0a,0x49,0x06,0x24,0x5c,0xc2,0xd3,0xac,0x62,0x91,0x95,0xe4,0x79,
    0xe7,0xc8,0x37,0x6d,0x8d,0xd5,0x4e,0xa9,0x6c,0x56,0xf4,0xea,0x65,0x7a,0xae,0x08,
    0xba,0x78,0x25,0x2e,0x1c,0xa6,0xb4,0xc6,0xe8,0xdd,0x74,0x1f,0x4b,0xbd,0x8b,0x8a,
    0x70,0x3e,0xb5,0x66,0x48,0x03,0xf6,0x0e,0x61,0x35,0x57,0xb9,0x86,0xc1,0x1d,0x9e,
    0xe1,0xf8,0x98,0x11,0x69,0xd9,0x8e,0x94,0x9b,0x1e,0x87,0xe9,0xce,0x55,0x28,0xdf,
    0x8c,0xa1,0x89,0x0d,0xbf,0xe6,0x42,0x68,0x41,0x99,0x2d,0x0f,0xb0,0x54,0xbb,0x16,
]

# AES Inverse S-Box
INV_SBOX = [0] * 256
for i in range(256):
    INV_SBOX[SBOX[i]] = i


def key_expansion_256(key):
    """AES-256 key schedule. Returns 15 round keys (each 16 bytes, round 0 = whitening)."""
    def sub_word(w):
        return ((SBOX[(w >> 24) & 0xFF] << 24) |
                (SBOX[(w >> 16) & 0xFF] << 16) |
                (SBOX[(w >> 8) & 0xFF] << 8) |
                (SBOX[w & 0xFF]))

    def rot_word(w):
        return ((w << 8) | (w >> 24)) & 0xFFFFFFFF

    RCON = [0x01, 0x02, 0x04, 0x08, 0x10, 0x20, 0x40, 0x80, 0x1B, 0x36, 0x6C, 0xD8, 0xAB, 0x4D, 0x9A]

    w = [0] * 60
    for i in range(8):
        w[i] = (key[i*4] << 24) | (key[i*4+1] << 16) | (key[i*4+2] << 8) | key[i*4+3]

    for i in range(8, 60):
        temp = w[i-1]
        if i % 8 == 0:
            temp = sub_word(rot_word(temp)) ^ (RCON[i // 8 - 1] << 24)
        elif i % 8 == 4:
            temp = sub_word(temp)
        w[i] = w[i-8] ^ temp

    round_keys = []
    for r in range(15):
        rk = b''
        for j in range(4):
            rk += w[r * 4 + j].to_bytes(4, 'big')
        round_keys.append(rk)
    return round_keys


def gf_mul(a, b):
    """Multiply in GF(2^8) with AES irreducible polynomial x^8 + x^4 + x^3 + x + 1"""
    p = 0
    for _ in range(8):
        if b & 1:
            p ^= a
        hi = a & 0x80
        a = (a << 1) & 0xFF
        if hi:
            a ^= 0x1B
        b >>= 1
    return p


def mix_columns_column(col):
    """MixColumns transform for 4 bytes (one column). Returns [c0', c1', c2', c3']"""
    return [
        gf_mul(col[0], 2) ^ gf_mul(col[1], 3) ^ col[2] ^ col[3],
        col[0] ^ gf_mul(col[1], 2) ^ gf_mul(col[2], 3) ^ col[3],
        col[0] ^ col[1] ^ gf_mul(col[2], 2) ^ gf_mul(col[3], 3),
        gf_mul(col[0], 3) ^ col[1] ^ col[2] ^ gf_mul(col[3], 2),
    ]


def inv_mix_columns_column(col):
    """InvMixColumns transform for 4 bytes (one column)."""
    return [
        gf_mul(col[0], 14) ^ gf_mul(col[1], 11) ^ gf_mul(col[2], 13) ^ gf_mul(col[3], 9),
        gf_mul(col[0], 9) ^ gf_mul(col[1], 14) ^ gf_mul(col[2], 11) ^ gf_mul(col[3], 13),
        gf_mul(col[0], 13) ^ gf_mul(col[1], 9) ^ gf_mul(col[2], 14) ^ gf_mul(col[3], 11),
        gf_mul(col[0], 11) ^ gf_mul(col[1], 13) ^ gf_mul(col[2], 9) ^ gf_mul(col[3], 14),
    ]


def generate_wb_tables(key_bytes, output_file=sys.stdout):
    """Main table generator — CORRECTED version."""
    import random
    random.seed(0xDEADBEEF)

    if len(key_bytes) != 32:
        raise ValueError("AES-256 requires 32-byte key")

    rks = key_expansion_256(key_bytes)
    out = output_file

    out.write('/* Auto-generated by gen_wb_tables.py — DO NOT EDIT */\n')
    out.write('#include <cstdint>\n\n')

    # ---- External encodings ----
    out.write('/* External input encodings (16 bytes XOR mask) */\n')
    ext_in = [random.randint(0, 255) for _ in range(16)]
    out.write('static const uint8_t g_wb_ext_in[16] = {')
    out.write(','.join(f'0x{b:02x}' for b in ext_in))
    out.write('};\n\n')

    out.write('/* External output encodings (16 bytes XOR mask) */\n')
    ext_out = [random.randint(0, 255) for _ in range(16)]
    out.write('static const uint8_t g_wb_ext_out[16] = {')
    out.write(','.join(f'0x{b:02x}' for b in ext_out))
    out.write('};\n\n')

    # ---- Forward T-Boxes (encrypt) ----
    # T-Box at position pos (row r = pos%4, col c = pos/4):
    #   T(x) = MixColumns_partial(SubBytes(x ^ round_key[pos])) at ShiftRows column
    #   After ShiftRows: byte at (r,c) goes to column (c-r) mod 4
    #   Output: 4 bytes representing this byte's contribution to that column's MixColumns output
    #
    # IMPORTANT: No AddRoundKey here! The round key is embedded INSIDE SubBytes.
    # The C++ encrypt function XORs 4 T-Box outputs per column, which gives
    # the complete MixColumns result for that column.
    # The final round (round 13) is handled differently: no MixColumns in the last round.
    # For simplicity, we use MixColumns for all rounds and adjust in C++.
    # (The C++ code handles the final round's ShiftRows separately if needed.)

    out.write('/* Forward T-Boxes: g_wb_tbox[round][position][256 entries × 4 bytes] */\n')
    out.write('/* Each entry = MixColumns contribution of SBOX[x ^ round_key[pos]] */\n')
    out.write('/* after ShiftRows moves byte to column (col-row) mod 4 */\n')
    out.write('static const uint8_t g_wb_tbox[14][16][1024] = {\n')

    for r in range(14):
        out.write(f'  /* Round {r} */ {{\n')
        rk = rks[r + 1]  # round key for this round (r=0 uses rk[1] since rk[0] is whitening)
        for pos in range(16):
            out.write(f'    /* Position {pos} */ {{\n')
            col = pos >> 2  # c = pos / 4
            row = pos & 3   # r = pos % 4
            sr_col = (col - row) & 3  # ShiftRows target column

            for x in range(256):
                # Correct Chow-style T-Box:
                # 1. XOR round key byte into input (embedded in SubBytes)
                xored = x ^ rk[pos]
                # 2. SubBytes
                sb = SBOX[xored]
                # 3. Build column input: only this byte's row is set
                col_in = [0, 0, 0, 0]
                col_in[row] = sb
                # 4. MixColumns
                mc = mix_columns_column(col_in)
                # Output: 4 bytes = contribution to column sr_col
                if x < 256:
                    out.write(f'      0x{mc[0]:02x},0x{mc[1]:02x},0x{mc[2]:02x},0x{mc[3]:02x}')
                    if x < 255:
                        out.write(',')
                    if (x + 1) % 4 == 0 and x < 255:
                        out.write('\n')
            out.write('    },\n')
        out.write('  },\n')
    out.write('};\n\n')

    # ---- Checksums from actual table data ----
    out.write('/* Anti-DFA checksums (XOR of all T-Box output bytes per round) */\n')
    out.write('static const uint8_t g_wb_checksum[14] = {\n')
    for r in range(14):
        cksum = 0
        rk = rks[r + 1]
        for pos in range(16):
            col = pos >> 2
            row = pos & 3
            sr_col = (col - row) & 3
            for x in range(256):
                xored = x ^ rk[pos]
                sb = SBOX[xored]
                col_in = [0, 0, 0, 0]
                col_in[row] = sb
                mc = mix_columns_column(col_in)
                cksum ^= mc[0] ^ mc[1] ^ mc[2] ^ mc[3]
        out.write(f'    0x{cksum:02x},\n')
    out.write('};\n\n')

    # ---- Inverse T-Boxes (decrypt) ----
    # InvT-Box: InvSubBytes(x ^ inv_round_key[pos]) → InvShiftRows → InvMixColumns
    # For inverse, we need the inverse round keys (last round's key is first)
    # The round key order for decryption: rk[14], rk[13], ..., rk[1]
    inv_rks = list(reversed(rks[1:]))  # 14 inverse round keys

    out.write('/* Inverse T-Boxes: g_wb_inv_tbox[round][position][256 entries × 4 bytes] */\n')
    out.write('/* Each entry = InvMixColumns contribution of INV_SBOX[x ^ inv_round_key[pos]] */\n')
    out.write('/* after InvShiftRows moves byte to column (col+row) mod 4 */\n')
    out.write('static const uint8_t g_wb_inv_tbox[14][16][1024] = {\n')

    for r in range(14):
        out.write(f'  /* Inverse round {r} */ {{\n')
        rk = inv_rks[r]  # inverse round key
        for pos in range(16):
            out.write(f'    /* Position {pos} */ {{\n')
            col = pos >> 2
            row = pos & 3
            isr_col = (col + row) & 3  # InvShiftRows target column

            for x in range(256):
                # InvSubBytes with embedded round key
                xored = x ^ rk[pos]
                isb = INV_SBOX[xored]
                col_in = [0, 0, 0, 0]
                col_in[row] = isb
                # InvMixColumns
                imc = inv_mix_columns_column(col_in)
                if x < 256:
                    out.write(f'      0x{imc[0]:02x},0x{imc[1]:02x},0x{imc[2]:02x},0x{imc[3]:02x}')
                    if x < 255:
                        out.write(',')
                    if (x + 1) % 4 == 0 and x < 255:
                        out.write('\n')
            out.write('    },\n')
        out.write('  },\n')
    out.write('};\n\n')

    # ---- Inverse checksums ----
    out.write('/* Anti-DFA checksums for inverse T-Boxes */\n')
    out.write('static const uint8_t g_wb_inv_checksum[14] = {\n')
    for r in range(14):
        cksum = 0
        rk = inv_rks[r]
        for pos in range(16):
            col = pos >> 2
            row = pos & 3
            isr_col = (col + row) & 3
            for x in range(256):
                xored = x ^ rk[pos]
                isb = INV_SBOX[xored]
                col_in = [0, 0, 0, 0]
                col_in[row] = isb
                imc = inv_mix_columns_column(col_in)
                cksum ^= imc[0] ^ imc[1] ^ imc[2] ^ imc[3]
        out.write(f'    0x{cksum:02x},\n')
    out.write('};\n\n')

    out.write('/* End of generated tables */\n')


def main():
    parser = argparse.ArgumentParser(description='Generate WB-AES tables (corrected)')
    parser.add_argument('--key', required=True,
                        help='Key: hex:<hex> or "random"')
    parser.add_argument('--output', '-o', default=None,
                        help='Output file (default: stdout)')
    args = parser.parse_args()

    if args.key == 'random':
        key = os.urandom(32)
        print(f'// Generated key: {key.hex()}', file=sys.stderr)
    elif args.key.startswith('hex:'):
        key = bytes.fromhex(args.key[4:])
        if len(key) != 32:
            print('Error: key must be 32 bytes (64 hex chars)', file=sys.stderr)
            sys.exit(1)
    else:
        key = sha256(args.key.encode()).digest()

    if args.output:
        with open(args.output, 'w') as f:
            generate_wb_tables(key, f)
        print(f'Tables written to {args.output}', file=sys.stderr)
    else:
        generate_wb_tables(key)


if __name__ == '__main__':
    main()
